// src/pages/Legal/LegalPages.tsx
import { useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import logoImg from "../../assets/icons/logo-bw.jpg";
import "./LegalPages.css";
import React from "react";


const D = { empresa: "One Life One Body", titular: "David Montero Blanco", nif: "XXXXXXXXX", dir: "Benidorm, Alicante, España", email: "d3ivins0n24@gmail.com", tel: "+34 631 98 63 91", web: "https://onelifeonebody.es" };

function Privacy() { return (<><h1 className="legal__title">Politica de Privacidad</h1><p className="legal__date">Actualizada: Mayo 2026</p><h2>1. Responsable</h2><p><b>Titular:</b> {D.titular} · <b>NIF:</b> {D.nif} · <b>Dirección:</b> {D.dir} · <b>Email:</b> {D.email}</p><h2>2. Datos que recopilamos</h2><ul><li><b>Identificación:</b> nombre, email, teléfono, fecha de nacimiento.</li><li><b>Salud y composición corporal:</b> peso, % grasa, % músculo, notas de evolución.</li><li><b>Uso:</b> reservas de pesaje, historial de citas, planes de alimentación.</li><li><b>Técnicos:</b> dirección IP (seguridad), tokens de sesión.</li></ul><h2>3. Finalidad</h2><ul><li>Gestionar tu cuenta y autenticación.</li><li>Seguimiento de composición corporal y evolución física.</li><li>Asignarte planes de alimentación personalizados.</li><li>Gestionar reservas de pesaje y enviar recordatorios.</li><li>Generar informes PDF de tu evolución.</li><li>Comunicarnos contigo (chatbot, email, WhatsApp).</li><li>Garantizar la seguridad de la plataforma.</li></ul><h2>4. Base legal</h2><ul><li><b>Consentimiento:</b> al registrarte aceptas el tratamiento.</li><li><b>Ejecución de contrato:</b> necesario para prestarte el servicio.</li><li><b>Interés legítimo:</b> seguridad y prevención de fraudes.</li></ul><h2>5. Conservación</h2><p>Tus datos se conservan mientras tu cuenta esté activa. Si solicitas eliminación, se borran en máximo 30 días. Logs de seguridad: 30 días con rotación automática.</p><h2>6. Destinatarios</h2><p>Tus datos NO se comparten con terceros, salvo:</p><ul><li><b>Google Gemini API:</b> mensajes del chatbot (sin datos personales).</li><li><b>Gmail SMTP:</b> envío de emails transaccionales.</li><li><b>Proveedor de hosting:</b> almacenamiento en sus servidores.</li></ul><h2>7. Tus derechos (RGPD)</h2><p>Tienes derecho a: <b>acceso, rectificación, supresión</b> ("derecho al olvido"), <b>limitación, portabilidad</b> y <b>oposición</b>. Contacta en {D.email}. Plazo de respuesta: 30 días. Puedes reclamar ante la <a href="https://www.aepd.es" target="_blank" rel="noreferrer">AEPD</a>.</p><h2>8. Seguridad</h2><ul><li>Contraseñas cifradas con bcrypt.</li><li>HTTPS/TLS en todas las comunicaciones.</li><li>Tokens con expiración.</li><li>Rate limiting contra ataques de fuerza bruta.</li><li>Headers de seguridad HTTP (HSTS, X-Frame-Options).</li><li>Logs de seguridad separados con rotación.</li></ul><h2>9. Menores</h2><p>Servicio dirigido a mayores de 16 años. Menores necesitan consentimiento de su tutor legal.</p><h2>10. Modificaciones</h2><p>Podemos modificar esta política. Los cambios se notificarán por la plataforma o email.</p></>); }

function Legal() { return (<><h1 className="legal__title">Aviso Legal</h1><p className="legal__date">Actualizada: Mayo 2026</p><h2>1. Datos identificativos</h2><p>En cumplimiento del art. 10 de la Ley 34/2002 (LSSICE):</p><ul><li><b>Titular:</b> {D.titular}</li><li><b>NIF:</b> {D.nif}</li><li><b>Domicilio:</b> {D.dir}</li><li><b>Email:</b> {D.email}</li><li><b>Teléfono:</b> {D.tel}</li><li><b>Web:</b> {D.web}</li></ul><h2>2. Objeto</h2><p>Ofrecer información sobre servicios de entrenamiento personal de {D.empresa} y proporcionar una plataforma para seguimiento de composición corporal, dietas y reservas.</p><h2>3. Propiedad intelectual</h2><p>Todos los contenidos (textos, imágenes, logos, código, diseño) son propiedad de {D.empresa}. Queda prohibida su reproducción sin autorización.</p><h2>4. Condiciones de uso</h2><ul><li>Uso adecuado conforme a la ley.</li><li>No realizar actividades ilícitas.</li><li>No intentar acceder a áreas restringidas.</li><li>No realizar ataques o inyecciones de código.</li><li>Proporcionar datos veraces.</li></ul><h2>5. Exclusión de responsabilidad</h2><p>{D.empresa} no se responsabiliza de: errores técnicos ajenos, contenido de webs enlazadas (BioTech USA, Instagram, WhatsApp), ni resultados físicos individuales.</p><h2>6. Legislación</h2><p>Se rige por la legislación española. Juzgados y Tribunales de Alicante.</p></>); }

function Cookies() { return (<><h1 className="legal__title">Politica de Cookies</h1><p className="legal__date">Actualizada: Mayo 2026</p><h2>1. Que son las cookies</h2><p>Archivos que los sitios web almacenan en tu navegador. Nosotros usamos localStorage y sessionStorage en lugar de cookies tradicionales.</p><h2>2. Que almacenamos</h2><h3>localStorage (persistente)</h3><ul><li><b>token:</b> Token de autenticación para mantener la sesión. Estrictamente necesario.</li><li><b>olob_access:</b> Código de acceso al área cliente.</li></ul><h3>Datos técnicos</h3><ul><li><b>IP:</b> para rate limiting y logs de seguridad (máx. 30 días).</li></ul><h2>3. Cookies de terceros</h2><p>NO usamos cookies de terceros, ni analítica, ni publicidad, ni redes sociales. No rastreamos tu actividad.</p><h2>4. Finalidad</h2><ul><li><b>Técnicas (necesarias):</b> token de sesión y código de acceso son imprescindibles.</li><li><b>Seguridad:</b> registro de IP para protección.</li></ul><h2>5. Como eliminarlos</h2><ul><li><b>Cerrar sesión:</b> elimina automáticamente token y código.</li><li><b>Manual:</b> Navegador → Configuración → Privacidad → Borrar datos.</li><li><b>Chrome:</b> F12 → Application → Local Storage → Clear.</li></ul><h2>6. Consentimiento</h2><p>Al usar la plataforma aceptas estas tecnologías estrictamente necesarias. No usamos cookies opcionales, por lo que no se requiere banner de cookies.</p></>); }

const PAGES: Record<string, { c: () => React.ReactElement }> = { "privacidad": { c: Privacy }, "aviso-legal": { c: Legal }, "cookies": { c: Cookies } };

export default function LegalPages() {
  const { page } = useParams<{ page: string }>();
  const p = PAGES[page || ""];
  useEffect(() => { window.scrollTo(0, 0); }, [page]);
  if (!p) return <div className="legal"><div className="legal__container"><h1 className="legal__title">No encontrada</h1><Link to="/" className="btn-primary" style={{ marginTop: "2rem" }}>Volver</Link></div></div>;
  const C = p.c;
  return (
    <div className="legal">
      <div className="legal__nav"><div className="container legal__nav-inner">
        <Link to="/" className="legal__logo"><img src={logoImg} alt="OLOB" /><span>ONE LIFE ONE BODY</span></Link>
        <div className="legal__nav-links">
          <Link to="/legal/privacidad" className={page === "privacidad" ? "active" : ""}>Privacidad</Link>
          <Link to="/legal/aviso-legal" className={page === "aviso-legal" ? "active" : ""}>Aviso legal</Link>
          <Link to="/legal/cookies" className={page === "cookies" ? "active" : ""}>Cookies</Link>
        </div>
      </div></div>
      <div className="legal__container"><C /><div className="legal__footer"><Link to="/" className="btn-ghost">← Volver a la web</Link><div className="legal__footer-links"><Link to="/legal/privacidad">Privacidad</Link><Link to="/legal/aviso-legal">Aviso legal</Link><Link to="/legal/cookies">Cookies</Link></div></div></div>
    </div>
  );
}